### ISSUE TITLE
Citation to the library

### ISSUE THREAD

**Issue by yzhao062** [OutlierDetectionJL/OutlierDetection.jl#26]
Great work! Just wondering if I want to cite this repo formally in a paper, what is the recommended citation (e.g., bib)? Thanks!

**Comment by davnn** [comment]
Hi, thank you for your great work in the field ;)

There is no official citation recommendation available at the moment, I would cite it as:

```
@article{muhrOutlierDetectionJlModular2022,
  title = {OutlierDetection.jl: A modular outlier detection ecosystem for the Julia programming language},
  author = {Muhr, David and Affenzeller, Michael and Anthony D., Blaom},
  year = {2022}
}
```

**Comment by yzhao062** [comment]
Thanks for the note and looking forward to the paper :) I will use the provided one for now.
